// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Goikoa.Domain.Navision.Producccion.DAL.Models;
using Microsoft.EntityFrameworkCore;

namespace Goikoa.Domain.Navision.Producccion.DAL.Context;

public partial class NAVBCContext : DbContext
{
    public NAVBCContext(DbContextOptions<NAVBCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GoikoaEscandalloFabricación> GoikoaEscandalloFabricacións { get; set; }

    public virtual DbSet<GoikoaItem> GoikoaItems { get; set; }

    public virtual DbSet<GoikoaItemCrossReference> GoikoaItemCrossReferences { get; set; }

    public virtual DbSet<GoikoaItemUnitOfMeasure> GoikoaItemUnitOfMeasures { get; set; }

    public virtual DbSet<GoikoaLineaPrevisionFabricacion> GoikoaLineaPrevisionFabricacions { get; set; }

    public virtual DbSet<GoikoaOrdenProducciónFabricación> GoikoaOrdenProducciónFabricacións { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Modern_Spanish_100_CI_AS");

        modelBuilder.Entity<GoikoaEscandalloFabricación>(entity =>
        {
            entity.HasKey(e => new { e.TipoOpFabric, e.NoOpFabric, e.PhaseCode, e.TaskCode, e.StepCode, e.LineNo }).HasName("GOIKOA$Escandallo fabricación$0");

            entity.ToTable("GOIKOA$Escandallo fabricación");

            entity.HasIndex(e => new { e.TipoOpFabric, e.NoOpFabric, e.Type, e.VendorNo, e.PhaseCode, e.TaskCode, e.StepCode, e.LineNo }, "$1").IsUnique();

            entity.HasIndex(e => new { e.TipoOpFabric, e.Type, e.No, e.VariantCode, e.Planificado, e.NoOpFabric, e.PhaseCode, e.TaskCode, e.StepCode, e.LineNo }, "$2").IsUnique();

            entity.HasIndex(e => new { e.Type, e.No, e.TipoOpFabric, e.NoOpFabric, e.PhaseCode, e.TaskCode, e.StepCode, e.LineNo }, "$3").IsUnique();

            entity.HasIndex(e => new { e.TipoOpFabric, e.NoOpFabric, e.Type, e.No, e.VariantCode, e.LocationCode, e.StartingDate, e.PhaseCode, e.TaskCode, e.StepCode, e.LineNo }, "$4").IsUnique();

            entity.HasIndex(e => new { e.TipoOpFabric, e.NoOpFabric, e.ProductoPrincipal, e.PhaseCode, e.TaskCode, e.StepCode, e.LineNo }, "$5").IsUnique();

            entity.HasIndex(e => new { e.TipoOpFabric, e.Type, e.No, e.Planificado, e.NoOpFabric, e.PhaseCode, e.TaskCode, e.StepCode, e.LineNo }, "$6").IsUnique();

            entity.HasIndex(e => new { e.NoOpFabric, e.LineNo, e.TipoOpFabric, e.PhaseCode, e.TaskCode, e.StepCode }, "$7").IsUnique();

            entity.Property(e => e.TipoOpFabric).HasColumnName("Tipo OP Fabric_");
            entity.Property(e => e.NoOpFabric)
                .HasMaxLength(20)
                .HasColumnName("No_ OP Fabric_");
            entity.Property(e => e.PhaseCode)
                .HasMaxLength(10)
                .HasColumnName("Phase Code");
            entity.Property(e => e.TaskCode)
                .HasMaxLength(10)
                .HasColumnName("Task Code");
            entity.Property(e => e.StepCode)
                .HasMaxLength(10)
                .HasColumnName("Step Code");
            entity.Property(e => e.LineNo).HasColumnName("Line No_");
            entity.Property(e => e.AcumulaEnKilos).HasColumnName("Acumula en kilos");
            entity.Property(e => e.AsociacionLote).HasColumnName("Asociacion Lote");
            entity.Property(e => e.BaseUnitOfMeasure)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Base Unit of Measure");
            entity.Property(e => e.BinCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Bin Code");
            entity.Property(e => e.BloquearAjusteAutCoste).HasColumnName("Bloquear ajuste aut_ coste");
            entity.Property(e => e.BloquearCantidad).HasColumnName("Bloquear cantidad");
            entity.Property(e => e.CantPrincipalSinRedondeo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cant_ Principal Sin Redondeo");
            entity.Property(e => e.CantidadConRechazo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad con rechazo");
            entity.Property(e => e.CantidadDosificacion)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad dosificacion");
            entity.Property(e => e.CantidadEmbalaje)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad Embalaje");
            entity.Property(e => e.CantidadKilos)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad Kilos");
            entity.Property(e => e.CantidadPor)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad por");
            entity.Property(e => e.CantidadUnidades)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad Unidades");
            entity.Property(e => e.CodAgrupacion)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cod_ agrupacion");
            entity.Property(e => e.CodigoEmbalaje)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Codigo Embalaje");
            entity.Property(e => e.ConsAutFlowpackYVacío).HasColumnName("Cons_ Aut_ Flowpack y Vacío");
            entity.Property(e => e.Consumo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Consumo");
            entity.Property(e => e.ConsumoAutomatico).HasColumnName("Consumo automatico");
            entity.Property(e => e.ConsumoComún).HasColumnName("Consumo Común");
            entity.Property(e => e.CosteUnidadMedidaBase)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Coste unidad medida base");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DíaDeLaSemana)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("Día de la semana");
            entity.Property(e => e.EndingDate)
                .HasColumnType("datetime")
                .HasColumnName("Ending Date");
            entity.Property(e => e.EndingTime)
                .HasColumnType("datetime")
                .HasColumnName("Ending Time");
            entity.Property(e => e.FaseEstadistica)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Fase estadistica");
            entity.Property(e => e.FechaFinalPlanificada)
                .HasColumnType("datetime")
                .HasColumnName("Fecha final planificada");
            entity.Property(e => e.FechaInicialPlanificada)
                .HasColumnType("datetime")
                .HasColumnName("Fecha inicial planificada");
            entity.Property(e => e.FechaTerminación)
                .HasColumnType("datetime")
                .HasColumnName("Fecha terminación");
            entity.Property(e => e.HoraFinalPlanificada)
                .HasColumnType("datetime")
                .HasColumnName("Hora final planificada");
            entity.Property(e => e.HoraInicialPlanificada)
                .HasColumnType("datetime")
                .HasColumnName("Hora inicial planificada");
            entity.Property(e => e.IngredienteBase).HasColumnName("Ingrediente Base");
            entity.Property(e => e.LocationCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Location Code");
            entity.Property(e => e.LotNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Lot No_");
            entity.Property(e => e.MargenInferiorConsumo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Margen inferior _ consumo");
            entity.Property(e => e.MargenSuperiorConsumo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Margen superior _ consumo");
            entity.Property(e => e.NetWeight)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Net Weight");
            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_");
            entity.Property(e => e.NoAplicarRechazo).HasColumnName("No Aplicar Rechazo");
            entity.Property(e => e.NoPresentacion)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ presentacion");
            entity.Property(e => e.Observaciones)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OrderDate)
                .HasColumnType("datetime")
                .HasColumnName("Order Date");
            entity.Property(e => e.OrderLineNo).HasColumnName("Order Line No_");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Order No_");
            entity.Property(e => e.PlazoOpFabric)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Plazo OP Fabric_");
            entity.Property(e => e.PlazoOpFabricHhMm)
                .HasColumnType("datetime")
                .HasColumnName("Plazo OP Fabric_ (hh:mm)");
            entity.Property(e => e.ProductoPrincipal).HasColumnName("Producto Principal");
            entity.Property(e => e.ProductoProveedor).HasColumnName("Producto proveedor");
            entity.Property(e => e.Quantity).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.RechazoConsumo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Rechazo consumo");
            entity.Property(e => e.RepartoConsumoRealizado).HasColumnName("Reparto Consumo Realizado");
            entity.Property(e => e.ResourceGroupNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Resource Group No_");
            entity.Property(e => e.StartingDate)
                .HasColumnType("datetime")
                .HasColumnName("Starting Date");
            entity.Property(e => e.StartingTime)
                .HasColumnType("datetime")
                .HasColumnName("Starting Time");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("timestamp");
            entity.Property(e => e.TipoRecurso).HasColumnName("Tipo recurso");
            entity.Property(e => e.Tolerancia).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.TotalCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Total Cost");
            entity.Property(e => e.UnitCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Unit Cost");
            entity.Property(e => e.VariantCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Variant Code");
            entity.Property(e => e.VendorNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Vendor No_");
            entity.Property(e => e.WorkCenterNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Work Center No_");
        });

        modelBuilder.Entity<GoikoaItem>(entity =>
        {
            entity.HasKey(e => e.No).HasName("GOIKOA$Item$0");

            entity.ToTable("GOIKOA$Item");

            entity.HasIndex(e => new { e.SearchDescription, e.No }, "$1").IsUnique();

            entity.HasIndex(e => new { e.CommonItemNo, e.No }, "$10").IsUnique();

            entity.HasIndex(e => new { e.ServiceItemGroup, e.No }, "$11").IsUnique();

            entity.HasIndex(e => new { e.CostIsAdjusted, e.AllowOnlineAdjustment, e.No }, "$12").IsUnique();

            entity.HasIndex(e => new { e.Description, e.No }, "$13").IsUnique();

            entity.HasIndex(e => new { e.BaseUnitOfMeasure, e.No }, "$14").IsUnique();

            entity.HasIndex(e => new { e.Type, e.No }, "$15").IsUnique();

            entity.HasIndex(e => new { e.ProductoOrigen, e.No }, "$16").IsUnique();

            entity.HasIndex(e => new { e.EdiCódigoEan, e.No }, "$17").IsUnique();

            entity.HasIndex(e => new { e.VisibleApp, e.ItemCategoryCode, e.No }, "$18").IsUnique();

            entity.HasIndex(e => new { e.VisibleApp, e.No }, "$19").IsUnique();

            entity.HasIndex(e => new { e.InventoryPostingGroup, e.No }, "$2").IsUnique();

            entity.HasIndex(e => new { e.ItemCategoryCode, e.No }, "$20").IsUnique();

            entity.HasIndex(e => new { e.Blocked, e.No }, "$21").IsUnique();

            entity.HasIndex(e => new { e.ShelfNo, e.No }, "$3").IsUnique();

            entity.HasIndex(e => new { e.VendorNo, e.No }, "$4").IsUnique();

            entity.HasIndex(e => new { e.GenProdPostingGroup, e.No }, "$5").IsUnique();

            entity.HasIndex(e => new { e.LowLevelCode, e.No }, "$6").IsUnique();

            entity.HasIndex(e => new { e.ProductionBomNo, e.No }, "$7").IsUnique();

            entity.HasIndex(e => new { e.RoutingNo, e.No }, "$8").IsUnique();

            entity.HasIndex(e => new { e.VendorItemNo, e.VendorNo, e.No }, "$9").IsUnique();

            entity.Property(e => e.No)
                .HasMaxLength(20)
                .HasColumnName("No_");
            entity.Property(e => e.Alegaciones)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.AllowInvoiceDisc).HasColumnName("Allow Invoice Disc_");
            entity.Property(e => e.AllowOnlineAdjustment).HasColumnName("Allow Online Adjustment");
            entity.Property(e => e.AlternativeItemNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Alternative Item No_");
            entity.Property(e => e.AnsCaducidadExped)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("ANS Caducidad exped_");
            entity.Property(e => e.AnsCaducidadRecep)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("ANS Caducidad recep_");
            entity.Property(e => e.ApplicationWkshUserId)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("Application Wksh_ User ID");
            entity.Property(e => e.AssemblyPolicy).HasColumnName("Assembly Policy");
            entity.Property(e => e.AutocompletarEmbalaje).HasColumnName("Autocompletar embalaje");
            entity.Property(e => e.AutomaticExtTexts).HasColumnName("Automatic Ext_ Texts");
            entity.Property(e => e.AvisoCalidad).HasColumnName("Aviso Calidad");
            entity.Property(e => e.BaseUnitOfMeasure)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Base Unit of Measure");
            entity.Property(e => e.BinCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Bin Code");
            entity.Property(e => e.BlockReason)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("Block Reason");
            entity.Property(e => e.BloquearAjusteAutCoste).HasColumnName("Bloquear ajuste aut_ coste");
            entity.Property(e => e.BrandType)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Brand Type");
            entity.Property(e => e.BudgetProfit)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Budget Profit");
            entity.Property(e => e.BudgetQuantity)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Budget Quantity");
            entity.Property(e => e.BudgetedAmount)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Budgeted Amount");
            entity.Property(e => e.CadastralReference)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cadastral Reference");
            entity.Property(e => e.CajasPorPalet).HasColumnName("Cajas por Palet");
            entity.Property(e => e.CantAlternativaObligatoria).HasColumnName("Cant_ alternativa obligatoria");
            entity.Property(e => e.CertificadoNoOgm)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Certificado No OGM");
            entity.Property(e => e.CodEmbalajeCompra)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cod_ Embalaje Compra");
            entity.Property(e => e.CodEspecie)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cod_ especie");
            entity.Property(e => e.CodGrupoIngredientes)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cod_ grupo ingredientes");
            entity.Property(e => e.CodPaletDefecto)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cod_ palet defecto");
            entity.Property(e => e.CodPlantilla)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cod_ Plantilla");
            entity.Property(e => e.CodigoPlu)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Codigo PLU");
            entity.Property(e => e.CommissionGroup).HasColumnName("Commission Group");
            entity.Property(e => e.CommodityCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Commodity Code");
            entity.Property(e => e.CommonItemNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Common Item No_");
            entity.Property(e => e.ControlDib).HasColumnName("Control DIB");
            entity.Property(e => e.ControlPor).HasColumnName("Control por");
            entity.Property(e => e.CostIsAdjusted).HasColumnName("Cost is Adjusted");
            entity.Property(e => e.CostRegulation)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cost Regulation _");
            entity.Property(e => e.CosteEstándarTeórico)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Coste Estándar Teórico");
            entity.Property(e => e.CosteIndirectoPorKilo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Coste indirecto por kilo");
            entity.Property(e => e.CosteIndirectoPorSobre)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Coste indirecto por sobre");
            entity.Property(e => e.CosteMedio)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Coste Medio");
            entity.Property(e => e.CostesPorCantidad)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Costes por cantidad");
            entity.Property(e => e.CostesPorCantidad1)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Costes por cantidad");
            entity.Property(e => e.CostesSecaderosPorKilo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Costes secaderos por kilo");
            entity.Property(e => e.CostingMethod).HasColumnName("Costing Method");
            entity.Property(e => e.CountryRegionOfOriginCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Country_Region of Origin Code");
            entity.Property(e => e.CountryRegionPurchasedCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Country_Region Purchased Code");
            entity.Property(e => e.CreatedFromNonstockItem).HasColumnName("Created From Nonstock Item");
            entity.Property(e => e.CódMáquina)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ Máquina");
            entity.Property(e => e.CódRappelCompras)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ rappel compras");
            entity.Property(e => e.CódRappelVentas)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ rappel ventas");
            entity.Property(e => e.CódigoEmbalaje)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Código Embalaje");
            entity.Property(e => e.DampenerPeriod)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Dampener Period");
            entity.Property(e => e.DampenerQuantity)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Dampener Quantity");
            entity.Property(e => e.DefaultDeferralTemplateCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Default Deferral Template Code");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description2)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Description 2");
            entity.Property(e => e.DesvCosteEstándarReal)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Desv_ Coste Estándar_Real");
            entity.Property(e => e.DiametroInterior)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Diametro interior");
            entity.Property(e => e.DiasDeCuracion).HasColumnName("Dias de curacion");
            entity.Property(e => e.DiferenciaKgAviso)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Diferencia Kg Aviso");
            entity.Property(e => e.DiferenciaKgError)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Diferencia Kg Error");
            entity.Property(e => e.DiscreteOrderQuantity).HasColumnName("Discrete Order Quantity");
            entity.Property(e => e.Durability)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.DutyCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Duty Code");
            entity.Property(e => e.DutyDue)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Duty Due _");
            entity.Property(e => e.DutyUnitConversion)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Duty Unit Conversion");
            entity.Property(e => e.DíasDeAnálisis).HasColumnName("Días de análisis");
            entity.Property(e => e.EdiCódigoEan)
                .IsRequired()
                .HasMaxLength(14)
                .HasColumnName("EDI Código EAN");
            entity.Property(e => e.EdiSalesUom).HasColumnName("EDI Sales UOM");
            entity.Property(e => e.Eficencia)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Eficencia");
            entity.Property(e => e.EmbEtiqueta)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Emb_ Etiqueta");
            entity.Property(e => e.ExpirationCalculation)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Expiration Calculation");
            entity.Property(e => e.FechaAlta)
                .HasColumnType("datetime")
                .HasColumnName("Fecha alta");
            entity.Property(e => e.FechaRevalorización)
                .HasColumnType("datetime")
                .HasColumnName("Fecha Revalorización");
            entity.Property(e => e.FlushingMethod).HasColumnName("Flushing Method");
            entity.Property(e => e.FreightType)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Freight Type");
            entity.Property(e => e.GenProdPostingGroup)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Gen_ Prod_ Posting Group");
            entity.Property(e => e.GlobalDimension1Code)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Global Dimension 1 Code");
            entity.Property(e => e.GlobalDimension2Code)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Global Dimension 2 Code");
            entity.Property(e => e.GlobalDimension6Code)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Global Dimension 6 Code");
            entity.Property(e => e.GlobalDimension7Code)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Global Dimension 7 Code");
            entity.Property(e => e.GlobalDimension8Code)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Global Dimension 8 Code");
            entity.Property(e => e.GrossWeight)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Gross Weight");
            entity.Property(e => e.GrupoResiduos)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Grupo residuos");
            entity.Property(e => e.Gtin)
                .IsRequired()
                .HasMaxLength(14)
                .HasColumnName("GTIN");
            entity.Property(e => e.IncludeInventory).HasColumnName("Include Inventory");
            entity.Property(e => e.IndirectCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Indirect Cost _");
            entity.Property(e => e.InventoryPostingGroup)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Inventory Posting Group");
            entity.Property(e => e.InventoryValueZero).HasColumnName("Inventory Value Zero");
            entity.Property(e => e.ItemCategoryCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Item Category Code");
            entity.Property(e => e.ItemCategoryId).HasColumnName("Item Category Id");
            entity.Property(e => e.ItemDiscGroup)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Item Disc_ Group");
            entity.Property(e => e.ItemTrackingCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Item Tracking Code");
            entity.Property(e => e.LastCountingPeriodUpdate)
                .HasColumnType("datetime")
                .HasColumnName("Last Counting Period Update");
            entity.Property(e => e.LastDateModified)
                .HasColumnType("datetime")
                .HasColumnName("Last Date Modified");
            entity.Property(e => e.LastDateTimeModified)
                .HasColumnType("datetime")
                .HasColumnName("Last DateTime Modified");
            entity.Property(e => e.LastDirectCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Last Direct Cost");
            entity.Property(e => e.LastTimeModified)
                .HasColumnType("datetime")
                .HasColumnName("Last Time Modified");
            entity.Property(e => e.LastUnitCostCalcDate)
                .HasColumnType("datetime")
                .HasColumnName("Last Unit Cost Calc_ Date");
            entity.Property(e => e.LeadTimeCalculation)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Lead Time Calculation");
            entity.Property(e => e.LiquidacionPorEmbalaje).HasColumnName("Liquidacion por embalaje");
            entity.Property(e => e.LiquidacionPorPesada).HasColumnName("Liquidacion por pesada");
            entity.Property(e => e.LocationCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Location Code");
            entity.Property(e => e.LotAccumulationPeriod)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Lot Accumulation Period");
            entity.Property(e => e.LotNos)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Lot Nos_");
            entity.Property(e => e.LotSize)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Lot Size");
            entity.Property(e => e.LowLevelCode).HasColumnName("Low-Level Code");
            entity.Property(e => e.MantenerLoteProveedor).HasColumnName("Mantener Lote Proveedor");
            entity.Property(e => e.ManufacturerCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Manufacturer Code");
            entity.Property(e => e.ManufacturingPolicy).HasColumnName("Manufacturing Policy");
            entity.Property(e => e.Marca)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.MargenInfCdadFabricada)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Margen inf_ Cdad_ fabricada");
            entity.Property(e => e.MargenInferiorConsumo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Margen inferior _ consumo");
            entity.Property(e => e.MargenInferiorPermitido)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Margen inferior permitido _");
            entity.Property(e => e.MargenSupCdadFabricada)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Margen sup_ Cdad_ fabricada");
            entity.Property(e => e.MargenSupConsDescuelgue)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Margen sup_ Cons_ Descuelgue");
            entity.Property(e => e.MargenSuperiorConsumo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Margen superior _ consumo");
            entity.Property(e => e.MargenSuperiorPermitido)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Margen superior permitido _");
            entity.Property(e => e.MaximumInventory)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Maximum Inventory");
            entity.Property(e => e.MaximumOrderQuantity)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Maximum Order Quantity");
            entity.Property(e => e.MermaLoncheado)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Merma loncheado");
            entity.Property(e => e.MermaTeórica)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Merma teórica");
            entity.Property(e => e.Micras).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.MinimumOrderQuantity)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Minimum Order Quantity");
            entity.Property(e => e.NaturalezaProducto)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Naturaleza Producto");
            entity.Property(e => e.NetWeight)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Net Weight");
            entity.Property(e => e.NextCountingEndDate)
                .HasColumnType("datetime")
                .HasColumnName("Next Counting End Date");
            entity.Property(e => e.NextCountingStartDate)
                .HasColumnType("datetime")
                .HasColumnName("Next Counting Start Date");
            entity.Property(e => e.No2)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ 2");
            entity.Property(e => e.NoPersonas)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("No_ Personas");
            entity.Property(e => e.NoPlantillaOtMatadero)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ plantilla OT Matadero");
            entity.Property(e => e.NoPresentacion)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ presentacion");
            entity.Property(e => e.NoSeries)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ Series");
            entity.Property(e => e.NombreAbreviado)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("Nombre abreviado");
            entity.Property(e => e.OEE)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("O_E_E_");
            entity.Property(e => e.OrderMultiple)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Order Multiple");
            entity.Property(e => e.OrderTrackingPolicy).HasColumnName("Order Tracking Policy");
            entity.Property(e => e.Origen)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OverflowLevel)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Overflow Level");
            entity.Property(e => e.OverheadRate)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Overhead Rate");
            entity.Property(e => e.PaisProcedencia)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Pais procedencia");
            entity.Property(e => e.PaletLogístico)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Palet Logístico");
            entity.Property(e => e.PaletPorDefecto)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Palet por defecto");
            entity.Property(e => e.PaletizacionAutomatica).HasColumnName("Paletizacion Automatica");
            entity.Property(e => e.PermitirReclasificaciónOc).HasColumnName("Permitir reclasificación OC");
            entity.Property(e => e.PesadaPorProductoLote).HasColumnName("Pesada por producto-lote");
            entity.Property(e => e.PesoFijo).HasColumnName("Peso fijo");
            entity.Property(e => e.PesoFijoEnVenta).HasColumnName("Peso fijo en venta");
            entity.Property(e => e.PesoMaxUnidad)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Peso max_ unidad");
            entity.Property(e => e.PesoMinUnidad)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Peso min_ unidad");
            entity.Property(e => e.PhysInvtCountingPeriodCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Phys Invt Counting Period Code");
            entity.Property(e => e.PlasticoMetrosKilo).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.PlasticosNoReciclado).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.PlazoConsumoPreferente)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Plazo consumo preferente");
            entity.Property(e => e.PlazoOpFabric)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Plazo OP Fabric_");
            entity.Property(e => e.PrecioMatadero)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Precio matadero");
            entity.Property(e => e.PrecioPuntoVerdeCdadDl)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Precio punto verde Cdad_ (DL)");
            entity.Property(e => e.PresenciaOgm).HasColumnName("Presencia OGM");
            entity.Property(e => e.PreventNegativeInventory).HasColumnName("Prevent Negative Inventory");
            entity.Property(e => e.PriceInAlternativeUnit).HasColumnName("Price in alternative Unit");
            entity.Property(e => e.PriceIncludesVat).HasColumnName("Price Includes VAT");
            entity.Property(e => e.PriceProfitCalculation).HasColumnName("Price_Profit Calculation");
            entity.Property(e => e.PriceUnitConversion).HasColumnName("Price Unit Conversion");
            entity.Property(e => e.ProductGroupCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Product Group Code");
            entity.Property(e => e.ProductionBomNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Production BOM No_");
            entity.Property(e => e.ProductoACurar).HasColumnName("Producto a curar");
            entity.Property(e => e.ProductoDeVenta).HasColumnName("Producto de venta");
            entity.Property(e => e.ProductoIberico).HasColumnName("Producto iberico");
            entity.Property(e => e.ProductoOrigen)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Producto origen");
            entity.Property(e => e.Profit)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Profit _");
            entity.Property(e => e.PropertySituation)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Property Situation");
            entity.Property(e => e.PurchUnitOfMeasure)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Purch_ Unit of Measure");
            entity.Property(e => e.PurchasingBlocked).HasColumnName("Purchasing Blocked");
            entity.Property(e => e.PutAwayTemplateCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Put-away Template Code");
            entity.Property(e => e.PutAwayUnitOfMeasureCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Put-away Unit of Measure Code");
            entity.Property(e => e.RechazoConsumo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Rechazo consumo");
            entity.Property(e => e.RedondeoCdadPrincipal)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Redondeo Cdad_ Principal");
            entity.Property(e => e.RegistroSanitario)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("Registro sanitario");
            entity.Property(e => e.ReorderPoint)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Reorder Point");
            entity.Property(e => e.ReorderQuantity)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Reorder Quantity");
            entity.Property(e => e.ReorderingPolicy).HasColumnName("Reordering Policy");
            entity.Property(e => e.ReplenishmentSystem).HasColumnName("Replenishment System");
            entity.Property(e => e.ReschedulingPeriod)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Rescheduling Period");
            entity.Property(e => e.RolledUpCapOverheadCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Rolled-up Cap_ Overhead Cost");
            entity.Property(e => e.RolledUpCapacityCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Rolled-up Capacity Cost");
            entity.Property(e => e.RolledUpMaterialCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Rolled-up Material Cost");
            entity.Property(e => e.RolledUpMfgOvhdCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Rolled-up Mfg_ Ovhd Cost");
            entity.Property(e => e.RolledUpSubcontractedCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Rolled-up Subcontracted Cost");
            entity.Property(e => e.RoundingPrecision)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Rounding Precision");
            entity.Property(e => e.RoutingNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Routing No_");
            entity.Property(e => e.SafetyLeadTime)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Safety Lead Time");
            entity.Property(e => e.SafetyStockQuantity)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Safety Stock Quantity");
            entity.Property(e => e.SalesBlocked).HasColumnName("Sales Blocked");
            entity.Property(e => e.SalesUnitOfMeasure)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Sales Unit of Measure");
            entity.Property(e => e.Scrap)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Scrap _");
            entity.Property(e => e.SearchDescription)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Search Description");
            entity.Property(e => e.SerialNos)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Serial Nos_");
            entity.Property(e => e.ServiceItemGroup)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Service Item Group");
            entity.Property(e => e.ShelfNo)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Shelf No_");
            entity.Property(e => e.SingleLevelCapOvhdCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Single-Level Cap_ Ovhd Cost");
            entity.Property(e => e.SingleLevelCapacityCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Single-Level Capacity Cost");
            entity.Property(e => e.SingleLevelMaterialCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Single-Level Material Cost");
            entity.Property(e => e.SingleLevelMfgOvhdCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Single-Level Mfg_ Ovhd Cost");
            entity.Property(e => e.SingleLevelSubcontrdCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Single-Level Subcontrd_ Cost");
            entity.Property(e => e.SobresObjetivoHora)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Sobres objetivo hora");
            entity.Property(e => e.SpecialEquipmentCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Special Equipment Code");
            entity.Property(e => e.StandardCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Standard Cost");
            entity.Property(e => e.StatisticsGroup).HasColumnName("Statistics Group");
            entity.Property(e => e.StockSeguridadProduccion)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Stock seguridad produccion");
            entity.Property(e => e.StockoutWarning).HasColumnName("Stockout Warning");
            entity.Property(e => e.Subfamilias)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TariffNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Tariff No_");
            entity.Property(e => e.TasaCostesIndirectos)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Tasa costes indirectos");
            entity.Property(e => e.TaxGroupCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Tax Group Code");
            entity.Property(e => e.TaxGroupId).HasColumnName("Tax Group Id");
            entity.Property(e => e.TemperaturaMaxima)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Temperatura Maxima");
            entity.Property(e => e.TemperaturaMinima)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Temperatura Minima");
            entity.Property(e => e.TextoEtiqueta)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Texto etiqueta");
            entity.Property(e => e.TiempoReposo)
                .HasColumnType("datetime")
                .HasColumnName("Tiempo Reposo");
            entity.Property(e => e.TimeBucket)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Time Bucket");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("timestamp");
            entity.Property(e => e.TipoBloqueo).HasColumnName("Tipo Bloqueo");
            entity.Property(e => e.TipoPaletizacion).HasColumnName("Tipo paletizacion");
            entity.Property(e => e.TipoPlantilla).HasColumnName("Tipo plantilla");
            entity.Property(e => e.TipoProducto)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Tipo Producto");
            entity.Property(e => e.Tolerancia).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.UdMedidaBaseEstándarHora)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Ud_ medida base estándar_hora");
            entity.Property(e => e.UnidadMedidaPuntoVerde)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Unidad medida punto verde");
            entity.Property(e => e.UnidadesPorCaja).HasColumnName("Unidades por Caja");
            entity.Property(e => e.UnitCost)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Unit Cost");
            entity.Property(e => e.UnitListPrice)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Unit List Price");
            entity.Property(e => e.UnitOfMeasureId).HasColumnName("Unit of Measure Id");
            entity.Property(e => e.UnitPrice)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Unit Price");
            entity.Property(e => e.UnitVolume)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Unit Volume");
            entity.Property(e => e.UnitsPerParcel)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Units per Parcel");
            entity.Property(e => e.UseCrossDocking).HasColumnName("Use Cross-Docking");
            entity.Property(e => e.UsuarioAlta)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Usuario alta");
            entity.Property(e => e.VatBusPostingGrPrice)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("VAT Bus_ Posting Gr_ (Price)");
            entity.Property(e => e.VatProdPostingGroup)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("VAT Prod_ Posting Group");
            entity.Property(e => e.VendorItemNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Vendor Item No_");
            entity.Property(e => e.VendorNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Vendor No_");
            entity.Property(e => e.VisibleApp).HasColumnName("Visible APP");
            entity.Property(e => e.WarehouseClassCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Warehouse Class Code");
            entity.Property(e => e.ZoneCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Zone Code");
        });

        modelBuilder.Entity<GoikoaItemCrossReference>(entity =>
        {
            entity.HasKey(e => new { e.ItemNo, e.VariantCode, e.UnitOfMeasure, e.CrossReferenceType, e.CrossReferenceTypeNo, e.CrossReferenceNo }).HasName("GOIKOA$Item Cross Reference$0");

            entity.ToTable("GOIKOA$Item Cross Reference");

            entity.HasIndex(e => new { e.CrossReferenceNo, e.ItemNo, e.VariantCode, e.UnitOfMeasure, e.CrossReferenceType, e.CrossReferenceTypeNo }, "$1").IsUnique();

            entity.HasIndex(e => new { e.CrossReferenceNo, e.CrossReferenceType, e.CrossReferenceTypeNo, e.DiscontinueBarCode, e.ItemNo, e.VariantCode, e.UnitOfMeasure }, "$2").IsUnique();

            entity.HasIndex(e => new { e.CrossReferenceType, e.CrossReferenceNo, e.ItemNo, e.VariantCode, e.UnitOfMeasure, e.CrossReferenceTypeNo }, "$3").IsUnique();

            entity.HasIndex(e => new { e.ItemNo, e.VariantCode, e.UnitOfMeasure, e.CrossReferenceType, e.CrossReferenceNo, e.DiscontinueBarCode, e.CrossReferenceTypeNo }, "$4").IsUnique();

            entity.HasIndex(e => new { e.CrossReferenceType, e.CrossReferenceTypeNo, e.ItemNo, e.VariantCode, e.UnitOfMeasure, e.CrossReferenceNo }, "$5").IsUnique();

            entity.Property(e => e.ItemNo)
                .HasMaxLength(20)
                .HasColumnName("Item No_");
            entity.Property(e => e.VariantCode)
                .HasMaxLength(10)
                .HasColumnName("Variant Code");
            entity.Property(e => e.UnitOfMeasure)
                .HasMaxLength(10)
                .HasColumnName("Unit of Measure");
            entity.Property(e => e.CrossReferenceType).HasColumnName("Cross-Reference Type");
            entity.Property(e => e.CrossReferenceTypeNo)
                .HasMaxLength(30)
                .HasColumnName("Cross-Reference Type No_");
            entity.Property(e => e.CrossReferenceNo)
                .HasMaxLength(20)
                .HasColumnName("Cross-Reference No_");
            entity.Property(e => e.AccountNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Account No_");
            entity.Property(e => e.AnsCaducidadExped)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("ANS Caducidad exped_");
            entity.Property(e => e.AnsCaducidadRecep)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("ANS Caducidad recep_");
            entity.Property(e => e.CustomerInternalNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Customer Internal No_");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description2)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Description 2");
            entity.Property(e => e.DiscontinueBarCode).HasColumnName("Discontinue Bar Code");
            entity.Property(e => e.Ean128Etiqueta)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("EAN128 Etiqueta");
            entity.Property(e => e.Ean13).HasColumnName("EAN13");
            entity.Property(e => e.EdiCódigoEan)
                .IsRequired()
                .HasMaxLength(17)
                .HasColumnName("EDI Código EAN");
            entity.Property(e => e.EdiCódigoProveedor)
                .IsRequired()
                .HasMaxLength(25)
                .HasColumnName("EDI Código PROVEEDOR");
            entity.Property(e => e.RelationType).HasColumnName("Relation Type");
            entity.Property(e => e.TheoreticalWeightUPacking)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Theoretical Weight U_ Packing");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("timestamp");
        });

        modelBuilder.Entity<GoikoaItemUnitOfMeasure>(entity =>
        {
            entity.HasKey(e => new { e.ItemNo, e.Code }).HasName("GOIKOA$Item Unit of Measure$0");

            entity.ToTable("GOIKOA$Item Unit of Measure");

            entity.HasIndex(e => new { e.ItemNo, e.QtyPerUnitOfMeasure, e.Code }, "$1").IsUnique();

            entity.HasIndex(e => new { e.Code, e.ItemNo }, "$2").IsUnique();

            entity.HasIndex(e => new { e.FormatoEcoembes, e.ItemNo, e.Code }, "$3").IsUnique();

            entity.Property(e => e.ItemNo)
                .HasMaxLength(20)
                .HasColumnName("Item No_");
            entity.Property(e => e.Code).HasMaxLength(10);
            entity.Property(e => e.CalculoCaducidadEtiqueta)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Calculo caducidad etiqueta");
            entity.Property(e => e.Conversión).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.Cubage).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.FormatoEcoembes)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Formato ECOEMBES");
            entity.Property(e => e.Height).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.IdentificadorTara)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Identificador Tara");
            entity.Property(e => e.Length).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.QtyPerUnitOfMeasure)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Qty_ per Unit of Measure");
            entity.Property(e => e.SistemaPesaje).HasColumnName("Sistema pesaje");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("timestamp");
            entity.Property(e => e.UnidadAlternativa).HasColumnName("Unidad Alternativa");
            entity.Property(e => e.UnidadesEnEmbalaje)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Unidades en embalaje");
            entity.Property(e => e.Weight).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.Width).HasColumnType("decimal(38, 20)");
        });

        modelBuilder.Entity<GoikoaLineaPrevisionFabricacion>(entity =>
        {
            entity.HasKey(e => new { e.NºPrevision, e.NºLinea }).HasName("GOIKOA$Linea Prevision Fabricacion$0");

            entity.ToTable("GOIKOA$Linea Prevision Fabricacion");

            entity.Property(e => e.NºPrevision)
                .HasMaxLength(20)
                .HasColumnName("Nº Prevision");
            entity.Property(e => e.NºLinea).HasColumnName("Nº Linea");
            entity.Property(e => e.AlmacenSalida)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Almacen Salida");
            entity.Property(e => e.CantidadAlternativa)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad Alternativa");
            entity.Property(e => e.CantidadEmbalaje)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad Embalaje");
            entity.Property(e => e.CantidadPrincipal)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad Principal");
            entity.Property(e => e.CentroTrabajo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Centro Trabajo");
            entity.Property(e => e.CodProducto)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cod_ Producto");
            entity.Property(e => e.CodVariante)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cod_ Variante");
            entity.Property(e => e.Comentarios)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.CódEquipo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ Equipo");
            entity.Property(e => e.CódPlantilla)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ Plantilla");
            entity.Property(e => e.CódigoEmbalaje)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Código Embalaje");
            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.FechaCaducidad)
                .HasColumnType("datetime")
                .HasColumnName("Fecha Caducidad");
            entity.Property(e => e.Grupo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.HorasTrabajo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Horas Trabajo");
            entity.Property(e => e.Linea)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Lote)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.NºOrdenProduccion)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Nº Orden Produccion");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("timestamp");
            entity.Property(e => e.TipoDestino).HasColumnName("Tipo Destino");
            entity.Property(e => e.TipoOrdenProduccion).HasColumnName("Tipo Orden Produccion");
            entity.Property(e => e.TipoPelado)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Tipo Pelado");
        });

        modelBuilder.Entity<GoikoaOrdenProducciónFabricación>(entity =>
        {
            entity.HasKey(e => new { e.Tipo, e.No }).HasName("GOIKOA$Orden producción fabricación$0");

            entity.ToTable("GOIKOA$Orden producción fabricación");

            entity.HasIndex(e => new { e.Tipo, e.Status, e.No }, "$1").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.VendorNo, e.Status, e.No }, "$10").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.ItemNo, e.Blocked, e.No }, "$11").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.SourceOrderNo, e.No }, "$12").IsUnique();

            entity.HasIndex(e => new { e.AjustarCoste, e.Tipo, e.No }, "$13").IsUnique();

            entity.HasIndex(e => new { e.NºPrevision, e.Tipo, e.No }, "$14").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.Status, e.FiltroGrupo, e.No }, "$15").IsUnique();

            entity.HasIndex(e => new { e.TipoDestino, e.ItemNo, e.NoLoteSalida, e.Tipo, e.No }, "$16").IsUnique();

            entity.HasIndex(e => new { e.Status, e.ItemNo, e.VariantCode, e.CódAlmacénSalidas, e.StartingDate, e.Tipo, e.No }, "$17").IsUnique();

            entity.HasIndex(e => new { e.Status, e.StartingDate, e.Tipo, e.No }, "$18").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.FiltroGrupo, e.No, e.Status }, "$19").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.Status, e.ItemNo, e.VariantCode, e.No }, "$2").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.NºPrevision, e.No }, "$20").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.TipoDestino, e.Status, e.StartingDate, e.CódAlmacénSalidas, e.No }, "$21").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.Blocked, e.TipoDestino, e.Status, e.StartingDate, e.No }, "$22").IsUnique();

            entity.HasIndex(e => new { e.No, e.Tipo }, "$23").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.Blocked, e.TipoDestino, e.Status, e.ItemNo, e.No }, "$24").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.ItemNo, e.VariantCode, e.No, e.Status }, "$3").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.CreationDate, e.No }, "$4").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.StartingDate, e.No }, "$5").IsUnique();

            entity.HasIndex(e => new { e.StartingDate, e.Tipo, e.No }, "$6").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.StartingDate, e.ItemNo, e.No }, "$7").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.ItemNo, e.VariantCode, e.StartingDate, e.No }, "$8").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.LineNo, e.FechaInicial1aPlanif, e.Priority, e.No }, "$9").IsUnique();

            entity.HasIndex(e => new { e.Tipo, e.TipoDestino, e.Status, e.CantidadAProducirUnid }, "BusquedaGoikoaNoItemPlantilla");

            entity.HasIndex(e => new { e.Tipo, e.TipoDestino, e.Status }, "BusquedaGoikoaPlantilla");

            entity.HasIndex(e => new { e.Tipo, e.TipoDestino, e.CódPlantillaProducción }, "BusquedaGoikoaStatus");

            entity.Property(e => e.No)
                .HasMaxLength(20)
                .HasColumnName("No_");
            entity.Property(e => e.AjustarCoste).HasColumnName("Ajustar coste");
            entity.Property(e => e.BillToCustomerNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Bill-to Customer No_");
            entity.Property(e => e.BillToName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Bill-to Name");
            entity.Property(e => e.BloquearAjusteCostes).HasColumnName("Bloquear ajuste costes");
            entity.Property(e => e.CalculoFabricacion).HasColumnName("Calculo fabricacion");
            entity.Property(e => e.CalculoTiempos).HasColumnName("Calculo tiempos");
            entity.Property(e => e.CantidadAProducir)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad a producir");
            entity.Property(e => e.CantidadAProducirEmbalajes)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad a producir Embalajes");
            entity.Property(e => e.CantidadAProducirUnid)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad a producir Unid_");
            entity.Property(e => e.CantidadBase)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad base");
            entity.Property(e => e.CantidadEmbalajeTeorico)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad Embalaje teorico");
            entity.Property(e => e.CantidadIngrediente)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad ingrediente");
            entity.Property(e => e.CantidadRelacion)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cantidad relacion");
            entity.Property(e => e.CdadAProducirTeorica)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cdad_ a producir teorica");
            entity.Property(e => e.CdadAProducirTeoricaUnid)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cdad_ a producir teorica Unid_");
            entity.Property(e => e.CdadAlternativaInicial)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cdad_ alternativa inicial");
            entity.Property(e => e.CdadEmbalajeInicial)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cdad_ embalaje inicial");
            entity.Property(e => e.CdadPrincipalInicial)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Cdad_ principal inicial");
            entity.Property(e => e.CodAlmacenDestino)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cod_ almacen destino");
            entity.Property(e => e.CodFormatoEtiqueta)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Cod_ formato etiqueta");
            entity.Property(e => e.CodIdiomaEtiquetaje)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cod_ idioma etiquetaje");
            entity.Property(e => e.CodIncidencia)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cod_ incidencia");
            entity.Property(e => e.CodigoEmbalaje)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Codigo Embalaje");
            entity.Property(e => e.Comentarios)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.ConsumoEstricto).HasColumnName("Consumo estricto");
            entity.Property(e => e.ConsumoProdsPrincipales)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Consumo Prods_ Principales");
            entity.Property(e => e.ControlConsumo).HasColumnName("Control Consumo");
            entity.Property(e => e.CostesPorCantidad)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Costes por cantidad");
            entity.Property(e => e.CostesPorCantidad1)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Costes por cantidad");
            entity.Property(e => e.CreationDate)
                .HasColumnType("datetime")
                .HasColumnName("Creation Date");
            entity.Property(e => e.CódAlmacénConsumos)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cód_ almacén consumos");
            entity.Property(e => e.CódAlmacénSalidas)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Cód_ almacén salidas");
            entity.Property(e => e.CódEquipo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ Equipo");
            entity.Property(e => e.CódPlantillaProducción)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ plantilla producción");
            entity.Property(e => e.CódPresentación)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ Presentación");
            entity.Property(e => e.CódResponsableTrabajo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ responsable trabajo");
            entity.Property(e => e.CódUbicaciónConsumos)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ Ubicación Consumos");
            entity.Property(e => e.CódUbicaciónSalidas)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Cód_ Ubicación Salidas");
            entity.Property(e => e.DescripcionIncidencia)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Descripcion incidencia");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Description2)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Description 2");
            entity.Property(e => e.DueDate)
                .HasColumnType("datetime")
                .HasColumnName("Due Date");
            entity.Property(e => e.EndingDate)
                .HasColumnType("datetime")
                .HasColumnName("Ending Date");
            entity.Property(e => e.EndingTime)
                .HasColumnType("datetime")
                .HasColumnName("Ending Time");
            entity.Property(e => e.EstadoTrabajo).HasColumnName("Estado trabajo");
            entity.Property(e => e.FechaCaducidadSalida)
                .HasColumnType("datetime")
                .HasColumnName("Fecha caducidad salida");
            entity.Property(e => e.FechaFinal1aPlanif)
                .HasColumnType("datetime")
                .HasColumnName("Fecha final 1a planif_");
            entity.Property(e => e.FechaHoraFinalizadasSalidas)
                .HasColumnType("datetime")
                .HasColumnName("Fecha Hora Finalizadas Salidas");
            entity.Property(e => e.FechaInicial1aPlanif)
                .HasColumnType("datetime")
                .HasColumnName("Fecha inicial 1a planif_");
            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Fecha modificacion");
            entity.Property(e => e.FechaTerminación)
                .HasColumnType("datetime")
                .HasColumnName("Fecha terminación");
            entity.Property(e => e.FechaValoracionCoste)
                .HasColumnType("datetime")
                .HasColumnName("Fecha valoracion coste");
            entity.Property(e => e.FiltroGrupo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Filtro Grupo");
            entity.Property(e => e.FinalizadaPdteConsumo).HasColumnName("Finalizada Pdte_ Consumo");
            entity.Property(e => e.GeneracionAutomOrden).HasColumnName("Generacion autom_ orden");
            entity.Property(e => e.HoraFinOperario)
                .HasColumnType("datetime")
                .HasColumnName("Hora fin operario");
            entity.Property(e => e.HoraFinal1aPlanif)
                .HasColumnType("datetime")
                .HasColumnName("Hora final 1a planif_");
            entity.Property(e => e.HoraInicial1aPlanif)
                .HasColumnType("datetime")
                .HasColumnName("Hora inicial 1a planif_");
            entity.Property(e => e.HoraInicioOperario)
                .HasColumnType("datetime")
                .HasColumnName("Hora inicio operario");
            entity.Property(e => e.ItemNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Item No_");
            entity.Property(e => e.KgHProduccionTeorica)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Kg_h produccion teorica");
            entity.Property(e => e.LastDateModified)
                .HasColumnType("datetime")
                .HasColumnName("Last Date Modified");
            entity.Property(e => e.LineNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Line No_");
            entity.Property(e => e.LineaBloqueada).HasColumnName("Linea bloqueada");
            entity.Property(e => e.MantenerNoLote).HasColumnName("Mantener No_ Lote");
            entity.Property(e => e.MermaTeórica)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("_ Merma teórica");
            entity.Property(e => e.Modificar1aPlanif).HasColumnName("Modificar 1a planif_");
            entity.Property(e => e.MultiploFabricacion)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Multiplo fabricacion");
            entity.Property(e => e.NoLineaPedido).HasColumnName("No_ linea Pedido");
            entity.Property(e => e.NoLoteSalida)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ Lote salida");
            entity.Property(e => e.NoOpFabricProducto)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ OP Fabric_ producto");
            entity.Property(e => e.NoOperarios).HasColumnName("No_ operarios");
            entity.Property(e => e.NoPanes)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("No_ Panes");
            entity.Property(e => e.NoPedidoVenta)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("No_ Pedido venta");
            entity.Property(e => e.NoPersonas)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("No_ Personas");
            entity.Property(e => e.NoPiezasPorPalet)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("No_ piezas por palet");
            entity.Property(e => e.NoPiezasPorPalo)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("No_ piezas por palo");
            entity.Property(e => e.NoSeries)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("No_ Series");
            entity.Property(e => e.NºLineaPrevision).HasColumnName("Nº Linea Prevision");
            entity.Property(e => e.NºPrevision)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Nº Prevision");
            entity.Property(e => e.Observacion)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OrdenDeAcabados).HasColumnName("Orden de acabados");
            entity.Property(e => e.PersonResponsible)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Person Responsible");
            entity.Property(e => e.PlazoOpCurac)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("Plazo OP Curac_");
            entity.Property(e => e.PlazoOpFabric)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Plazo OP Fabric_");
            entity.Property(e => e.PlazoOpFabricHhMm)
                .HasColumnType("datetime")
                .HasColumnName("Plazo OP Fabric_ (hh:mm)");
            entity.Property(e => e.RegistrarConsSalOaConj).HasColumnName("Registrar cons_-sal_ OA conj_");
            entity.Property(e => e.RepartoConsumoRealizado).HasColumnName("Reparto Consumo Realizado");
            entity.Property(e => e.SearchDescription)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Search Description");
            entity.Property(e => e.SemanaInicial).HasColumnName("Semana inicial");
            entity.Property(e => e.SemanaInicialPlanificada).HasColumnName("Semana inicial planificada");
            entity.Property(e => e.SourceOrderNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Source Order No_");
            entity.Property(e => e.StartingDate)
                .HasColumnType("datetime")
                .HasColumnName("Starting Date");
            entity.Property(e => e.StartingTime)
                .HasColumnType("datetime")
                .HasColumnName("Starting Time");
            entity.Property(e => e.Temperatura).HasColumnType("decimal(38, 20)");
            entity.Property(e => e.TiempoProduccion).HasColumnType("datetime");
            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("timestamp");
            entity.Property(e => e.TipoCaja)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Tipo caja");
            entity.Property(e => e.TipoDestino).HasColumnName("Tipo destino");
            entity.Property(e => e.TipoPalet)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Tipo palet");
            entity.Property(e => e.TipoPelado)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Tipo Pelado");
            entity.Property(e => e.TurnoTrabajo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Turno trabajo");
            entity.Property(e => e.UnidadesDosificadas).HasColumnName("Unidades dosificadas");
            entity.Property(e => e.UnidadesFabricacion2)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Unidades fabricacion 2");
            entity.Property(e => e.UsarAlmacénUbicaciónPesada).HasColumnName("Usar Almacén_Ubicación Pesada");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("User ID");
            entity.Property(e => e.ValidaciónSalidas).HasColumnName("Validación Salidas");
            entity.Property(e => e.ValorManoObraDirecta)
                .HasColumnType("decimal(38, 20)")
                .HasColumnName("Valor mano obra directa");
            entity.Property(e => e.VariantCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Variant Code");
            entity.Property(e => e.VendorNo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Vendor No_");
            entity.Property(e => e.Version)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.WorkCenterNo)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Work Center No_");
            entity.Property(e => e.YourReference)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Your Reference");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}