// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.Navision.Producccion.DAL.Models;

public partial class GoikoaItem
{
    public byte[] Timestamp { get; set; }

    public string No { get; set; }

    public string No2 { get; set; }

    public string Description { get; set; }

    public string SearchDescription { get; set; }

    public string Description2 { get; set; }

    public string BaseUnitOfMeasure { get; set; }

    public int PriceUnitConversion { get; set; }

    public int Type { get; set; }

    public string InventoryPostingGroup { get; set; }

    public string ShelfNo { get; set; }

    public string ItemDiscGroup { get; set; }

    public byte AllowInvoiceDisc { get; set; }

    public int StatisticsGroup { get; set; }

    public int CommissionGroup { get; set; }

    public decimal UnitPrice { get; set; }

    public int PriceProfitCalculation { get; set; }

    public decimal Profit { get; set; }

    public int CostingMethod { get; set; }

    public decimal UnitCost { get; set; }

    public decimal StandardCost { get; set; }

    public decimal LastDirectCost { get; set; }

    public decimal IndirectCost { get; set; }

    public byte CostIsAdjusted { get; set; }

    public byte AllowOnlineAdjustment { get; set; }

    public string VendorNo { get; set; }

    public string VendorItemNo { get; set; }

    public string LeadTimeCalculation { get; set; }

    public decimal ReorderPoint { get; set; }

    public decimal MaximumInventory { get; set; }

    public decimal ReorderQuantity { get; set; }

    public string AlternativeItemNo { get; set; }

    public decimal UnitListPrice { get; set; }

    public decimal DutyDue { get; set; }

    public string DutyCode { get; set; }

    public decimal GrossWeight { get; set; }

    public decimal NetWeight { get; set; }

    public decimal UnitsPerParcel { get; set; }

    public decimal UnitVolume { get; set; }

    public string Durability { get; set; }

    public string FreightType { get; set; }

    public string TariffNo { get; set; }

    public decimal DutyUnitConversion { get; set; }

    public string CountryRegionPurchasedCode { get; set; }

    public decimal BudgetQuantity { get; set; }

    public decimal BudgetedAmount { get; set; }

    public decimal BudgetProfit { get; set; }

    public byte Blocked { get; set; }

    public string BlockReason { get; set; }

    public DateTime LastDateTimeModified { get; set; }

    public DateTime LastDateModified { get; set; }

    public DateTime LastTimeModified { get; set; }

    public byte PriceIncludesVat { get; set; }

    public string VatBusPostingGrPrice { get; set; }

    public string GenProdPostingGroup { get; set; }

    public Guid Picture { get; set; }

    public string CountryRegionOfOriginCode { get; set; }

    public byte AutomaticExtTexts { get; set; }

    public string NoSeries { get; set; }

    public string TaxGroupCode { get; set; }

    public string VatProdPostingGroup { get; set; }

    public int Reserve { get; set; }

    public string GlobalDimension1Code { get; set; }

    public string GlobalDimension2Code { get; set; }

    public int StockoutWarning { get; set; }

    public int PreventNegativeInventory { get; set; }

    public string ApplicationWkshUserId { get; set; }

    public int AssemblyPolicy { get; set; }

    public string Gtin { get; set; }

    public string DefaultDeferralTemplateCode { get; set; }

    public int LowLevelCode { get; set; }

    public decimal LotSize { get; set; }

    public string SerialNos { get; set; }

    public DateTime LastUnitCostCalcDate { get; set; }

    public decimal RolledUpMaterialCost { get; set; }

    public decimal RolledUpCapacityCost { get; set; }

    public decimal Scrap { get; set; }

    public byte InventoryValueZero { get; set; }

    public int DiscreteOrderQuantity { get; set; }

    public decimal MinimumOrderQuantity { get; set; }

    public decimal MaximumOrderQuantity { get; set; }

    public decimal SafetyStockQuantity { get; set; }

    public decimal OrderMultiple { get; set; }

    public string SafetyLeadTime { get; set; }

    public int FlushingMethod { get; set; }

    public int ReplenishmentSystem { get; set; }

    public decimal RoundingPrecision { get; set; }

    public string SalesUnitOfMeasure { get; set; }

    public string PurchUnitOfMeasure { get; set; }

    public string TimeBucket { get; set; }

    public int ReorderingPolicy { get; set; }

    public byte IncludeInventory { get; set; }

    public int ManufacturingPolicy { get; set; }

    public string ReschedulingPeriod { get; set; }

    public string LotAccumulationPeriod { get; set; }

    public string DampenerPeriod { get; set; }

    public decimal DampenerQuantity { get; set; }

    public decimal OverflowLevel { get; set; }

    public string ManufacturerCode { get; set; }

    public string ItemCategoryCode { get; set; }

    public byte CreatedFromNonstockItem { get; set; }

    public string ProductGroupCode { get; set; }

    public string ServiceItemGroup { get; set; }

    public string ItemTrackingCode { get; set; }

    public string LotNos { get; set; }

    public string ExpirationCalculation { get; set; }

    public string WarehouseClassCode { get; set; }

    public string SpecialEquipmentCode { get; set; }

    public string PutAwayTemplateCode { get; set; }

    public string PutAwayUnitOfMeasureCode { get; set; }

    public string PhysInvtCountingPeriodCode { get; set; }

    public DateTime LastCountingPeriodUpdate { get; set; }

    public byte UseCrossDocking { get; set; }

    public DateTime NextCountingStartDate { get; set; }

    public DateTime NextCountingEndDate { get; set; }

    public Guid Id { get; set; }

    public Guid UnitOfMeasureId { get; set; }

    public Guid TaxGroupId { get; set; }

    public byte SalesBlocked { get; set; }

    public byte PurchasingBlocked { get; set; }

    public Guid ItemCategoryId { get; set; }

    public decimal CostRegulation { get; set; }

    public int TipoPlantilla { get; set; }

    public decimal NoPersonas { get; set; }

    public int TipoBloqueo { get; set; }

    public decimal MargenInferiorConsumo { get; set; }

    public decimal MargenSuperiorConsumo { get; set; }

    public decimal RechazoConsumo { get; set; }

    public string GlobalDimension7Code { get; set; }

    public string GlobalDimension8Code { get; set; }

    public decimal UdMedidaBaseEstándarHora { get; set; }

    public decimal SobresObjetivoHora { get; set; }

    public byte PriceInAlternativeUnit { get; set; }

    public decimal Micras { get; set; }

    public decimal DiametroInterior { get; set; }

    public int DíasDeAnálisis { get; set; }

    public byte VisibleApp { get; set; }

    public decimal RedondeoCdadPrincipal { get; set; }

    public decimal MermaLoncheado { get; set; }

    public decimal Eficencia { get; set; }

    public decimal CosteIndirectoPorSobre { get; set; }

    public decimal CostesSecaderosPorKilo { get; set; }

    public decimal CosteIndirectoPorKilo { get; set; }

    public decimal CosteEstándarTeórico { get; set; }

    public decimal CosteMedio { get; set; }

    public decimal DesvCosteEstándarReal { get; set; }

    public decimal DiferenciaKgAviso { get; set; }

    public decimal DiferenciaKgError { get; set; }

    public decimal OEE { get; set; }

    public string CódMáquina { get; set; }

    public string PaletLogístico { get; set; }

    public decimal MargenInfCdadFabricada { get; set; }

    public decimal MargenSupCdadFabricada { get; set; }

    public byte Mantenimiento { get; set; }

    public string CódRappelVentas { get; set; }

    public string CódRappelCompras { get; set; }

    public string NoPresentacion { get; set; }

    public string CódigoEmbalaje { get; set; }

    public int ControlDib { get; set; }

    public decimal PrecioPuntoVerdeCdadDl { get; set; }

    public string UnidadMedidaPuntoVerde { get; set; }

    public string GrupoResiduos { get; set; }

    public byte AutocompletarEmbalaje { get; set; }

    public string AnsCaducidadRecep { get; set; }

    public string AnsCaducidadExped { get; set; }

    public byte LiquidacionPorEmbalaje { get; set; }

    public byte PesoFijo { get; set; }

    public byte LiquidacionPorPesada { get; set; }

    public string NombreAbreviado { get; set; }

    public byte CantAlternativaObligatoria { get; set; }

    public string CodigoPlu { get; set; }

    public string RegistroSanitario { get; set; }

    public string CodEmbalajeCompra { get; set; }

    public string CodPaletDefecto { get; set; }

    public int TipoPaletizacion { get; set; }

    public string PaletPorDefecto { get; set; }

    public byte PesadaPorProductoLote { get; set; }

    public byte ProductoDeVenta { get; set; }

    public string PlazoConsumoPreferente { get; set; }

    public string Marca { get; set; }

    public DateTime FechaAlta { get; set; }

    public string UsuarioAlta { get; set; }

    public byte PesoFijoEnVenta { get; set; }

    public byte ProductoIberico { get; set; }

    public string CodGrupoIngredientes { get; set; }

    public decimal StockSeguridadProduccion { get; set; }

    public string NaturalezaProducto { get; set; }

    public decimal TemperaturaMinima { get; set; }

    public decimal TemperaturaMaxima { get; set; }

    public byte BloquearAjusteAutCoste { get; set; }

    public decimal MermaTeórica { get; set; }

    public string PlazoOpFabric { get; set; }

    public string ProductoOrigen { get; set; }

    public decimal CostesPorCantidad { get; set; }

    public decimal CostesPorCantidad1 { get; set; }

    public int UnidadesPorCaja { get; set; }

    public int CajasPorPalet { get; set; }

    public decimal PesoMinUnidad { get; set; }

    public decimal PesoMaxUnidad { get; set; }

    public decimal Tolerancia { get; set; }

    public byte PresenciaOgm { get; set; }

    public string PaisProcedencia { get; set; }

    public string CertificadoNoOgm { get; set; }

    public string TextoEtiqueta { get; set; }

    public string Origen { get; set; }

    public string CodPlantilla { get; set; }

    public DateTime TiempoReposo { get; set; }

    public string LocationCode { get; set; }

    public byte PermitirReclasificaciónOc { get; set; }

    public byte AvisoCalidad { get; set; }

    public string EmbEtiqueta { get; set; }

    public byte ProductoACurar { get; set; }

    public byte PaletizacionAutomatica { get; set; }

    public int DiasDeCuracion { get; set; }

    public decimal MargenSuperiorPermitido { get; set; }

    public decimal MargenInferiorPermitido { get; set; }

    public decimal PrecioMatadero { get; set; }

    public string CodEspecie { get; set; }

    public int ControlPor { get; set; }

    public string NoPlantillaOtMatadero { get; set; }

    public string EdiCódigoEan { get; set; }

    public string PropertySituation { get; set; }

    public string RoutingNo { get; set; }

    public string ProductionBomNo { get; set; }

    public decimal SingleLevelMaterialCost { get; set; }

    public decimal SingleLevelCapacityCost { get; set; }

    public decimal SingleLevelSubcontrdCost { get; set; }

    public decimal SingleLevelCapOvhdCost { get; set; }

    public decimal SingleLevelMfgOvhdCost { get; set; }

    public decimal OverheadRate { get; set; }

    public decimal RolledUpSubcontractedCost { get; set; }

    public decimal RolledUpMfgOvhdCost { get; set; }

    public decimal RolledUpCapOverheadCost { get; set; }

    public int OrderTrackingPolicy { get; set; }

    public byte Critical { get; set; }

    public string CommonItemNo { get; set; }

    public decimal MargenSupConsDescuelgue { get; set; }

    public string CommodityCode { get; set; }

    public string ZoneCode { get; set; }

    public string BinCode { get; set; }

    public string BrandType { get; set; }

    public int EdiSalesUom { get; set; }

    public string TipoProducto { get; set; }

    public DateTime FechaRevalorización { get; set; }

    public string GlobalDimension6Code { get; set; }

    public string Alegaciones { get; set; }

    public string Subfamilias { get; set; }

    public byte MantenerLoteProveedor { get; set; }

    public decimal PlasticoMetrosKilo { get; set; }

    public decimal PlasticosNoReciclado { get; set; }

    public string CadastralReference { get; set; }

    public decimal TasaCostesIndirectos { get; set; }
}