// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.Navision.Producccion.DAL.Models;

public partial class GoikoaEscandalloFabricación
{
    public byte[] Timestamp { get; set; }

    public int TipoOpFabric { get; set; }

    public string NoOpFabric { get; set; }

    public string PhaseCode { get; set; }

    public string TaskCode { get; set; }

    public string StepCode { get; set; }

    public int LineNo { get; set; }

    public int Type { get; set; }

    public string No { get; set; }

    public string VariantCode { get; set; }

    public string Description { get; set; }

    public string LocationCode { get; set; }

    public string LotNo { get; set; }

    public decimal Quantity { get; set; }

    public string BaseUnitOfMeasure { get; set; }

    public byte BloquearAjusteAutCoste { get; set; }

    public decimal UnitCost { get; set; }

    public decimal TotalCost { get; set; }

    public int TipoRecurso { get; set; }

    public string ResourceGroupNo { get; set; }

    public string VendorNo { get; set; }

    public string WorkCenterNo { get; set; }

    public DateTime StartingDate { get; set; }

    public DateTime EndingDate { get; set; }

    public DateTime FechaInicialPlanificada { get; set; }

    public DateTime FechaFinalPlanificada { get; set; }

    public byte Terminada { get; set; }

    public decimal NetWeight { get; set; }

    public decimal CantidadUnidades { get; set; }

    public decimal CantidadKilos { get; set; }

    public byte BloquearCantidad { get; set; }

    public DateTime FechaTerminación { get; set; }

    public string PlazoOpFabric { get; set; }

    public decimal CantidadEmbalaje { get; set; }

    public byte ConsumoAutomatico { get; set; }

    public decimal Tolerancia { get; set; }

    public string OrderNo { get; set; }

    public int OrderLineNo { get; set; }

    public string CodigoEmbalaje { get; set; }

    public string NoPresentacion { get; set; }

    public string Observaciones { get; set; }

    public DateTime StartingTime { get; set; }

    public DateTime EndingTime { get; set; }

    public DateTime HoraInicialPlanificada { get; set; }

    public DateTime HoraFinalPlanificada { get; set; }

    public DateTime PlazoOpFabricHhMm { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal CantidadDosificacion { get; set; }

    public byte IngredienteBase { get; set; }

    public byte ProductoProveedor { get; set; }

    public byte Recalculo { get; set; }

    public string CodAgrupacion { get; set; }

    public byte AcumulaEnKilos { get; set; }

    public string FaseEstadistica { get; set; }

    public byte ProductoPrincipal { get; set; }

    public decimal Consumo { get; set; }

    public string BinCode { get; set; }

    public byte ConsumoComún { get; set; }

    public decimal CantidadPor { get; set; }

    public decimal RechazoConsumo { get; set; }

    public decimal MargenInferiorConsumo { get; set; }

    public decimal MargenSuperiorConsumo { get; set; }

    public byte RepartoConsumoRealizado { get; set; }

    public byte NoAplicarRechazo { get; set; }

    public int Semana { get; set; }

    public string DíaDeLaSemana { get; set; }

    public decimal CantPrincipalSinRedondeo { get; set; }

    public byte Planificado { get; set; }

    public byte AsociacionLote { get; set; }

    public decimal CantidadConRechazo { get; set; }

    public decimal CosteUnidadMedidaBase { get; set; }

    public byte ConsAutFlowpackYVacío { get; set; }
}