// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.Navision.Producccion.DAL.Models;

public partial class GoikoaOrdenProducciónFabricación
{
    public byte[] Timestamp { get; set; }

    public int Tipo { get; set; }

    public string No { get; set; }

    public string SearchDescription { get; set; }

    public string Description { get; set; }

    public string Description2 { get; set; }

    public DateTime CreationDate { get; set; }

    public DateTime LastDateModified { get; set; }

    public byte Blocked { get; set; }

    public int Status { get; set; }

    public string PersonResponsible { get; set; }

    public int EstadoTrabajo { get; set; }

    public string CódResponsableTrabajo { get; set; }

    public DateTime StartingDate { get; set; }

    public DateTime EndingDate { get; set; }

    public DateTime DueDate { get; set; }

    public string ItemNo { get; set; }

    public string VariantCode { get; set; }

    public int TipoDestino { get; set; }

    public decimal CantidadAProducir { get; set; }

    public decimal CantidadAProducirUnid { get; set; }

    public string CódPresentación { get; set; }

    public string NoLoteSalida { get; set; }

    public string CódAlmacénConsumos { get; set; }

    public string CódAlmacénSalidas { get; set; }

    public string NoPedidoVenta { get; set; }

    public int NoLineaPedido { get; set; }

    public string BillToCustomerNo { get; set; }

    public string BillToName { get; set; }

    public string YourReference { get; set; }

    public string CódPlantillaProducción { get; set; }

    public decimal MermaTeórica { get; set; }

    public string NoSeries { get; set; }

    public DateTime FechaTerminación { get; set; }

    public string PlazoOpFabric { get; set; }

    public string NoOpFabricProducto { get; set; }

    public byte OrdenDeAcabados { get; set; }

    public DateTime FechaCaducidadSalida { get; set; }

    public decimal CantidadBase { get; set; }

    public decimal NoPanes { get; set; }

    public decimal CostesPorCantidad { get; set; }

    public decimal CostesPorCantidad1 { get; set; }

    public decimal CdadAProducirTeorica { get; set; }

    public decimal CdadAProducirTeoricaUnid { get; set; }

    public string CodFormatoEtiqueta { get; set; }

    public string CodigoEmbalaje { get; set; }

    public decimal CantidadAProducirEmbalajes { get; set; }

    public decimal CantidadEmbalajeTeorico { get; set; }

    public string CodIdiomaEtiquetaje { get; set; }

    public byte RegistrarConsSalOaConj { get; set; }

    public byte Servicio { get; set; }

    public string LineNo { get; set; }

    public string WorkCenterNo { get; set; }

    public DateTime StartingTime { get; set; }

    public DateTime EndingTime { get; set; }

    public DateTime PlazoOpFabricHhMm { get; set; }

    public int Priority { get; set; }

    public DateTime FechaInicial1aPlanif { get; set; }

    public DateTime HoraInicial1aPlanif { get; set; }

    public DateTime FechaFinal1aPlanif { get; set; }

    public DateTime HoraFinal1aPlanif { get; set; }

    public decimal MultiploFabricacion { get; set; }

    public string CodIncidencia { get; set; }

    public string DescripcionIncidencia { get; set; }

    public byte LineaBloqueada { get; set; }

    public string Version { get; set; }

    public string Observacion { get; set; }

    public string UserId { get; set; }

    public DateTime FechaModificacion { get; set; }

    public int NoOperarios { get; set; }

    public decimal KgHProduccionTeorica { get; set; }

    public DateTime HoraInicioOperario { get; set; }

    public DateTime HoraFinOperario { get; set; }

    public int CalculoTiempos { get; set; }

    public int UnidadesDosificadas { get; set; }

    public byte Modificar1aPlanif { get; set; }

    public int CalculoFabricacion { get; set; }

    public decimal CantidadIngrediente { get; set; }

    public byte BloquearAjusteCostes { get; set; }

    public string SourceOrderNo { get; set; }

    public decimal UnidadesFabricacion2 { get; set; }

    public byte ConsumoEstricto { get; set; }

    public string PlazoOpCurac { get; set; }

    public byte GeneracionAutomOrden { get; set; }

    public string TipoPalet { get; set; }

    public string TipoCaja { get; set; }

    public decimal CantidadRelacion { get; set; }

    public decimal NoPiezasPorPalet { get; set; }

    public int SemanaInicialPlanificada { get; set; }

    public int SemanaInicial { get; set; }

    public byte AjustarCoste { get; set; }

    public string CodAlmacenDestino { get; set; }

    public string VendorNo { get; set; }

    public DateTime FechaValoracionCoste { get; set; }

    public decimal ConsumoProdsPrincipales { get; set; }

    public string CódUbicaciónConsumos { get; set; }

    public decimal NoPiezasPorPalo { get; set; }

    public string CódUbicaciónSalidas { get; set; }

    public byte FinalizadaPdteConsumo { get; set; }

    public decimal NoPersonas { get; set; }

    public byte UsarAlmacénUbicaciónPesada { get; set; }

    public string FiltroGrupo { get; set; }

    public DateTime FechaHoraFinalizadasSalidas { get; set; }

    public string NºPrevision { get; set; }

    public int NºLineaPrevision { get; set; }

    public string Comentarios { get; set; }

    public string TipoPelado { get; set; }

    public byte MantenerNoLote { get; set; }

    public byte RepartoConsumoRealizado { get; set; }

    public byte ValidaciónSalidas { get; set; }

    public decimal Temperatura { get; set; }

    public string TurnoTrabajo { get; set; }

    public int Orden { get; set; }

    public decimal ValorManoObraDirecta { get; set; }

    public string CódEquipo { get; set; }

    public byte ControlConsumo { get; set; }

    public decimal CdadEmbalajeInicial { get; set; }

    public decimal CdadPrincipalInicial { get; set; }

    public decimal CdadAlternativaInicial { get; set; }

    public DateTime TiempoProduccion { get; set; }
}