// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.Navision.Producccion.DAL.Models;

public partial class GoikoaItemUnitOfMeasure
{
    public byte[] Timestamp { get; set; }

    public string ItemNo { get; set; }

    public string Code { get; set; }

    public decimal QtyPerUnitOfMeasure { get; set; }

    public decimal Length { get; set; }

    public decimal Width { get; set; }

    public decimal Height { get; set; }

    public decimal Cubage { get; set; }

    public decimal Weight { get; set; }

    public string FormatoEcoembes { get; set; }

    public byte UnidadAlternativa { get; set; }

    public decimal UnidadesEnEmbalaje { get; set; }

    public byte SistemaPesaje { get; set; }

    public string CalculoCaducidadEtiqueta { get; set; }

    public string IdentificadorTara { get; set; }

    public decimal Conversión { get; set; }
}