// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.Navision.Producccion.DAL.Models;

public partial class GoikoaLineaPrevisionFabricacion
{
    public byte[] Timestamp { get; set; }

    public string NºPrevision { get; set; }

    public int NºLinea { get; set; }

    public DateTime Fecha { get; set; }

    public int TipoDestino { get; set; }

    public string CodProducto { get; set; }

    public string AlmacenSalida { get; set; }

    public string CentroTrabajo { get; set; }

    public string Linea { get; set; }

    public string Grupo { get; set; }

    public int TipoOrdenProduccion { get; set; }

    public string NºOrdenProduccion { get; set; }

    public decimal CantidadPrincipal { get; set; }

    public decimal CantidadAlternativa { get; set; }

    public int Orden { get; set; }

    public DateTime FechaCaducidad { get; set; }

    public string Lote { get; set; }

    public string Comentarios { get; set; }

    public string CodVariante { get; set; }

    public string TipoPelado { get; set; }

    public string CódigoEmbalaje { get; set; }

    public decimal CantidadEmbalaje { get; set; }

    public string CódEquipo { get; set; }

    public decimal HorasTrabajo { get; set; }

    public string CódPlantilla { get; set; }
}