// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.Navision.Producccion.DAL.Models;

public partial class GoikoaItemCrossReference
{
    public byte[] Timestamp { get; set; }

    public string ItemNo { get; set; }

    public string VariantCode { get; set; }

    public string UnitOfMeasure { get; set; }

    public int CrossReferenceType { get; set; }

    public string CrossReferenceTypeNo { get; set; }

    public string CrossReferenceNo { get; set; }

    public string Description { get; set; }

    public byte DiscontinueBarCode { get; set; }

    public string Description2 { get; set; }

    public decimal TheoreticalWeightUPacking { get; set; }

    public string AnsCaducidadRecep { get; set; }

    public string AnsCaducidadExped { get; set; }

    public string Ean128Etiqueta { get; set; }

    public int RelationType { get; set; }

    public string AccountNo { get; set; }

    public string EdiCódigoEan { get; set; }

    public string EdiCódigoProveedor { get; set; }

    public byte Ean13 { get; set; }

    public byte Documentos { get; set; }

    public string CustomerInternalNo { get; set; }
}