// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class CamposNavision
{
    public int PK_IdCampoNavision { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Campo> Campo { get; set; } = new List<Campo>();
}