// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class CamposWSBartender
{
    public int Id { get; set; }

    public string NombreCampoBartender { get; set; }

    public DateTime FechaRegistro { get; set; }

    public bool EstaEnWS { get; set; }
}