// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class Campo
{
    public int PK_IdCampo { get; set; }

    public string NombreCampo { get; set; }

    public int? FK_IdTipoCampo { get; set; }

    public bool? IsNavision { get; set; }

    public int? FK_IdCampoNavision { get; set; }

    public virtual ICollection<EtiquetaCamposValores> EtiquetaCamposValores { get; set; } = new List<EtiquetaCamposValores>();

    public virtual CamposNavision FK_IdCampoNavisionNavigation { get; set; }

    public virtual TiposCampo FK_IdTipoCampoNavigation { get; set; }

    public virtual ICollection<PlantillaCampos> PlantillaCampos { get; set; } = new List<PlantillaCampos>();
}