// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class CodificacionTiposCodigoBarras
{
    public int Id { get; set; }

    public string NumeroIdentificacion { get; set; }

    public string NombrePropiedad { get; set; }
}