// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class EtiquetaLabels
{
    public int PK_IdEtiquetaLabel { get; set; }

    public int FK_IdEtiqueta { get; set; }

    public int FK_IdTipoLabel { get; set; }

    public int FK_IdIdioma { get; set; }

    public int FK_IdLabel { get; set; }

    public int? Orden { get; set; }

    public virtual Etiqueta FK_IdEtiquetaNavigation { get; set; }

    public virtual IdiomasLabels FK_IdIdiomaNavigation { get; set; }

    public virtual LabelsMaster FK_IdLabelNavigation { get; set; }

    public virtual TiposLabels FK_IdTipoLabelNavigation { get; set; }
}