// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class EtiquetaCamposValores
{
    public int PK_IdEtiquetaCampoValor { get; set; }

    public int? FK_IdEtiqueta { get; set; }

    public int? FK_IdCampo { get; set; }

    public string ValorCampo { get; set; }

    public string NombreCampoDespuesDeBorrado { get; set; }

    public virtual Campo FK_IdCampoNavigation { get; set; }

    public virtual Etiqueta FK_IdEtiquetaNavigation { get; set; }
}