// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class EtiquetaCodigosBarra
{
    public int PK_IdEtiquetaCodigoBarra { get; set; }

    public int FK_IdEtiqueta { get; set; }

    public int FK_IdTipoCodigoBarra { get; set; }

    public int Orden { get; set; }

    public virtual Etiqueta FK_IdEtiquetaNavigation { get; set; }

    public virtual TiposCodigoBarra FK_IdTipoCodigoBarraNavigation { get; set; }
}