// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class Etiqueta
{
    public int PK_IdEtiqueta { get; set; }

    public int FK_IdPlantilla { get; set; }

    public int? FK_IdTipoEtiqueta { get; set; }

    public int? FK_IdConservacion { get; set; }

    public int? FK_IdSeccion { get; set; }

    public int? FK_IdCliente { get; set; }

    public DateTime? FechaGeneracion { get; set; }

    public string Comentario { get; set; }

    public int? FK_IdEnvasado { get; set; }

    public string NombreEtiqueta { get; set; }

    public string CodigoProducto { get; set; }

    public int? Version { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string OvaloIdioma { get; set; }

    public string OvaloPlanta { get; set; }

    public string OvaloCE { get; set; }

    public string Usuario { get; set; }

    public int? FK_IdUbicacion { get; set; }

    public virtual ICollection<EtiquetaCamposValores> EtiquetaCamposValores { get; set; } = new List<EtiquetaCamposValores>();

    public virtual ICollection<EtiquetaCodigosBarra> EtiquetaCodigosBarra { get; set; } = new List<EtiquetaCodigosBarra>();

    public virtual ICollection<EtiquetaLabels> EtiquetaLabels { get; set; } = new List<EtiquetaLabels>();

    public virtual Cliente FK_IdClienteNavigation { get; set; }

    public virtual TiposConservacion FK_IdConservacionNavigation { get; set; }

    public virtual TiposEnvasado FK_IdEnvasadoNavigation { get; set; }

    public virtual Plantilla FK_IdPlantillaNavigation { get; set; }

    public virtual Secciones FK_IdSeccionNavigation { get; set; }

    public virtual TiposEtiqueta FK_IdTipoEtiquetaNavigation { get; set; }

    public virtual Ubicaciones FK_IdUbicacionNavigation { get; set; }

    public virtual ICollection<HistoricoImpresion> HistoricoImpresion { get; set; } = new List<HistoricoImpresion>();
}