// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class IdiomasLabels
{
    public int PK_IdIdioma { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<EtiquetaLabels> EtiquetaLabels { get; set; } = new List<EtiquetaLabels>();

    public virtual ICollection<LabelsMaster> LabelsMaster { get; set; } = new List<LabelsMaster>();
}