// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class LabelsMaster
{
    public int PK_IdLabel { get; set; }

    public int FK_IdTipoLabel { get; set; }

    public int FK_IdIdioma { get; set; }

    public string DescripcionLabel { get; set; }

    public virtual ICollection<EtiquetaLabels> EtiquetaLabels { get; set; } = new List<EtiquetaLabels>();

    public virtual IdiomasLabels FK_IdIdiomaNavigation { get; set; }

    public virtual TiposLabels FK_IdTipoLabelNavigation { get; set; }
}