// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class PlantillaCampos
{
    public int PK_IdPlantillaCampo { get; set; }

    public int FK_IdPlantilla { get; set; }

    public int? FK_IdCampo { get; set; }

    public string NombreCampoBartender { get; set; }

    public int? Orden { get; set; }

    public bool? EsObligatorio { get; set; }

    public virtual Campo FK_IdCampoNavigation { get; set; }

    public virtual Plantilla FK_IdPlantillaNavigation { get; set; }
}