// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class Plantilla
{
    public int PK_IdPlantilla { get; set; }

    public string NombrePlantilla { get; set; }

    public string RutaArchivo { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual ICollection<Etiqueta> Etiqueta { get; set; } = new List<Etiqueta>();

    public virtual ICollection<PlantillaCampos> PlantillaCampos { get; set; } = new List<PlantillaCampos>();
}