// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class TiposCodigoBarra
{
    public int PK_IdTipoCodigoBarra { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<EtiquetaCodigosBarra> EtiquetaCodigosBarra { get; set; } = new List<EtiquetaCodigosBarra>();
}