// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Models;

public partial class Ubicaciones
{
    public int PK_IdUbicacion { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Etiqueta> Etiqueta { get; set; } = new List<Etiqueta>();
}