// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.ApiAdmin.DAL.Models;

public partial class Log
{
    public int Id { get; set; }

    public string Message { get; set; }

    public string MessageTemplate { get; set; }

    public string Level { get; set; }

    public DateTimeOffset TimeStamp { get; set; }

    public string Exception { get; set; }

    public string Properties { get; set; }

    public string LogEvent { get; set; }
}