// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.ApiAdmin.DAL.Models;

public partial class RefreshToken
{
    public int Id { get; set; }

    public string Token { get; set; }

    public DateTime Created { get; set; }

    public DateTime Expires { get; set; }

    public DateTime? Revoked { get; set; }

    public int UserId { get; set; }

    public string ReplacedByToken { get; set; }

    public virtual Usuario User { get; set; }
}