// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.ApiAdmin.DAL.Models;

public partial class Usuario
{
    public int PkIdUser { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int? FkRoleId { get; set; }

    public virtual Role FkRole { get; set; }

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();
}