// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.ApiAdmin.DAL.Models;

public partial class VisionOrdenResuman
{
    public Guid Id { get; set; }

    public string OrdenFabricacion { get; set; }

    public string CodigoProducto { get; set; }

    public string DescripcionProducto { get; set; }

    public DateTime? FechaProduccion { get; set; }

    public string Linea { get; set; }

    public string TipoEtiqueta { get; set; }

    public string PosicionQr { get; set; }

    public string CodigoEsperado { get; set; }

    public DateTime FechaHoraInicio { get; set; }

    public DateTime? FechaHoraUltimaLectura { get; set; }

    public int TotalLecturas { get; set; }

    public int TotalOk { get; set; }

    public int TotalNok { get; set; }

    public bool Activa { get; set; }

    public string IpCamara { get; set; }

    public virtual ICollection<VisionLectura> VisionLecturas { get; set; } = new List<VisionLectura>();
}