// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Goikoa.Domain.ApiAdmin.DAL.Models;

public partial class VisionLectura
{
    public Guid Id { get; set; }

    public Guid VisionOrdenResumenId { get; set; }

    public DateTime FechaHoraLectura { get; set; }

    public string CodigoEsperado { get; set; }

    public string CodigoLeido { get; set; }

    public string Resultado { get; set; }

    public string RawMensaje { get; set; }

    public string Observaciones { get; set; }

    public string TipoEtiqueta { get; set; }

    public virtual VisionOrdenResuman VisionOrdenResumen { get; set; }
}