// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Goikoa.Domain.ApiAdmin.DAL.Models;
using Microsoft.EntityFrameworkCore;

namespace Goikoa.Domain.ApiAdmin.DAL.Context;

public partial class ApiAdminContext : DbContext
{
    public ApiAdminContext(DbContextOptions<ApiAdminContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<VisionLectura> VisionLecturas { get; set; }

    public virtual DbSet<VisionOrdenResuman> VisionOrdenResumen { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Log>(entity =>
        {
            entity.Property(e => e.Level).HasMaxLength(128);
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RefreshT__3214EC076B12AF27");

            entity.HasIndex(e => e.Expires, "IX_RefreshTokens_Expiration");

            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.Expires).HasColumnType("datetime");
            entity.Property(e => e.Revoked).HasColumnType("datetime");
            entity.Property(e => e.Token).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RefreshTo__UserI__4AB81AF0");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.PkIdRole).HasName("PK__Roles__64E5DFF3D4DC2E3B");

            entity.Property(e => e.PkIdRole).HasColumnName("PK_Id_Role");
            entity.Property(e => e.NombreRol)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nombre_Rol");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.PkIdUser).HasName("PK__Usuarios__7FCEE39CC8F223D9");

            entity.HasIndex(e => e.Username, "UQ__Usuarios__536C85E4190EC985").IsUnique();

            entity.Property(e => e.PkIdUser).HasColumnName("Pk_Id_User");
            entity.Property(e => e.FkRoleId).HasColumnName("FK_Role_Id");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.FkRole).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.FkRoleId)
                .HasConstraintName("FK__Usuarios__FK_Rol__3A81B327");
        });

        modelBuilder.Entity<VisionLectura>(entity =>
        {
            entity.ToTable("VisionLectura");

            entity.HasIndex(e => e.VisionOrdenResumenId, "IX_VisionLectura_VisionOrdenResumenId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CodigoEsperado)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.CodigoLeido)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.FechaHoraLectura)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Observaciones).HasMaxLength(500);
            entity.Property(e => e.Resultado)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.TipoEtiqueta).HasMaxLength(50);

            entity.HasOne(d => d.VisionOrdenResumen).WithMany(p => p.VisionLecturas)
                .HasForeignKey(d => d.VisionOrdenResumenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VisionLectura_VisionOrdenResumen");
        });

        modelBuilder.Entity<VisionOrdenResuman>(entity =>
        {
            entity.HasIndex(e => new { e.OrdenFabricacion, e.Activa }, "IX_VisionOrdenResumen_OrdenFabricacion_Activa");

            entity.HasIndex(e => new { e.OrdenFabricacion, e.IpCamara }, "IX_VisionOrdenResumen_OrdenFabricacion_IpCamara");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Activa).HasDefaultValue(true);
            entity.Property(e => e.CodigoEsperado)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.CodigoProducto)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DescripcionProducto)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FechaHoraInicio)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FechaHoraUltimaLectura).HasPrecision(0);
            entity.Property(e => e.FechaProduccion).HasPrecision(0);
            entity.Property(e => e.IpCamara).HasMaxLength(100);
            entity.Property(e => e.Linea).HasMaxLength(50);
            entity.Property(e => e.OrdenFabricacion)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PosicionQr).HasMaxLength(20);
            entity.Property(e => e.TipoEtiqueta)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TotalNok).HasColumnName("TotalNOK");
            entity.Property(e => e.TotalOk).HasColumnName("TotalOK");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}