// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Goikoa.Domain.GestionEtiquetas.DAL.Models;
using Microsoft.EntityFrameworkCore;

namespace Goikoa.Domain.GestionEtiquetas.DAL.Context;

public partial class BDGestionEtiquetasContext : DbContext
{
    public BDGestionEtiquetasContext(DbContextOptions<BDGestionEtiquetasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Campo> Campo { get; set; }

    public virtual DbSet<CamposNavision> CamposNavision { get; set; }

    public virtual DbSet<CamposWSBartender> CamposWSBartender { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<CodificacionTiposCodigoBarras> CodificacionTiposCodigoBarras { get; set; }

    public virtual DbSet<Etiqueta> Etiqueta { get; set; }

    public virtual DbSet<EtiquetaCamposValores> EtiquetaCamposValores { get; set; }

    public virtual DbSet<EtiquetaCodigosBarra> EtiquetaCodigosBarra { get; set; }

    public virtual DbSet<EtiquetaLabels> EtiquetaLabels { get; set; }

    public virtual DbSet<HistoricoImpresion> HistoricoImpresion { get; set; }

    public virtual DbSet<IdiomasLabels> IdiomasLabels { get; set; }

    public virtual DbSet<LabelsMaster> LabelsMaster { get; set; }

    public virtual DbSet<Plantilla> Plantilla { get; set; }

    public virtual DbSet<PlantillaCampos> PlantillaCampos { get; set; }

    public virtual DbSet<Secciones> Secciones { get; set; }

    public virtual DbSet<TiposCampo> TiposCampo { get; set; }

    public virtual DbSet<TiposCodigoBarra> TiposCodigoBarra { get; set; }

    public virtual DbSet<TiposConservacion> TiposConservacion { get; set; }

    public virtual DbSet<TiposEnvasado> TiposEnvasado { get; set; }

    public virtual DbSet<TiposEtiqueta> TiposEtiqueta { get; set; }

    public virtual DbSet<TiposLabels> TiposLabels { get; set; }

    public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Campo>(entity =>
        {
            entity.HasKey(e => e.PK_IdCampo).HasName("PK__Campos__35AB96F0FA61582B");

            entity.Property(e => e.NombreCampo).HasMaxLength(100);

            entity.HasOne(d => d.FK_IdCampoNavisionNavigation).WithMany(p => p.Campo)
                .HasForeignKey(d => d.FK_IdCampoNavision)
                .HasConstraintName("FK_Campos_CamposNavision");

            entity.HasOne(d => d.FK_IdTipoCampoNavigation).WithMany(p => p.Campo)
                .HasForeignKey(d => d.FK_IdTipoCampo)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Campos_TipoCampo");
        });

        modelBuilder.Entity<CamposNavision>(entity =>
        {
            entity.HasKey(e => e.PK_IdCampoNavision).HasName("PK__CamposNa__D9E43055069BAAD0");

            entity.HasIndex(e => e.Descripcion, "UQ__CamposNa__92C53B6C47A6DE4B").IsUnique();

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<CamposWSBartender>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CamposWS__3214EC073E8B0F3D");

            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");
            entity.Property(e => e.NombreCampoBartender)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.PK_IdCliente).HasName("PK__MarcasCo__F88C7B18F1AF8E18");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<CodificacionTiposCodigoBarras>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CodigosI__3214EC0764DDC357");

            entity.Property(e => e.NombrePropiedad)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NumeroIdentificacion)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<Etiqueta>(entity =>
        {
            entity.HasKey(e => e.PK_IdEtiqueta).HasName("PK__Etiqueta__FCAFF6B0836067B5");

            entity.Property(e => e.CodigoProducto)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Comentario).HasMaxLength(250);
            entity.Property(e => e.FechaGeneracion).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.NombreEtiqueta)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OvaloCE)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OvaloIdioma)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.OvaloPlanta)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Usuario).HasMaxLength(50);

            entity.HasOne(d => d.FK_IdClienteNavigation).WithMany(p => p.Etiqueta)
                .HasForeignKey(d => d.FK_IdCliente)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Etiqueta_Marca");

            entity.HasOne(d => d.FK_IdConservacionNavigation).WithMany(p => p.Etiqueta)
                .HasForeignKey(d => d.FK_IdConservacion)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Etiqueta_Conservacion");

            entity.HasOne(d => d.FK_IdEnvasadoNavigation).WithMany(p => p.Etiqueta)
                .HasForeignKey(d => d.FK_IdEnvasado)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Envasado_Etiqueta");

            entity.HasOne(d => d.FK_IdPlantillaNavigation).WithMany(p => p.Etiqueta)
                .HasForeignKey(d => d.FK_IdPlantilla)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Etiqueta_Plantilla");

            entity.HasOne(d => d.FK_IdSeccionNavigation).WithMany(p => p.Etiqueta)
                .HasForeignKey(d => d.FK_IdSeccion)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Etiqueta_Seccion");

            entity.HasOne(d => d.FK_IdTipoEtiquetaNavigation).WithMany(p => p.Etiqueta)
                .HasForeignKey(d => d.FK_IdTipoEtiqueta)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Etiqueta_TipoEtiqueta");

            entity.HasOne(d => d.FK_IdUbicacionNavigation).WithMany(p => p.Etiqueta)
                .HasForeignKey(d => d.FK_IdUbicacion)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Etiqueta_Ubicacion");
        });

        modelBuilder.Entity<EtiquetaCamposValores>(entity =>
        {
            entity.HasKey(e => e.PK_IdEtiquetaCampoValor).HasName("PK__Etiqueta__06A6EFD249A495EB");

            entity.Property(e => e.NombreCampoDespuesDeBorrado).HasMaxLength(100);

            entity.HasOne(d => d.FK_IdCampoNavigation).WithMany(p => p.EtiquetaCamposValores)
                .HasForeignKey(d => d.FK_IdCampo)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_EtiquetaValor_Campo");

            entity.HasOne(d => d.FK_IdEtiquetaNavigation).WithMany(p => p.EtiquetaCamposValores)
                .HasForeignKey(d => d.FK_IdEtiqueta)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_EtiquetaValor_Etiqueta");
        });

        modelBuilder.Entity<EtiquetaCodigosBarra>(entity =>
        {
            entity.HasKey(e => e.PK_IdEtiquetaCodigoBarra);

            entity.HasOne(d => d.FK_IdEtiquetaNavigation).WithMany(p => p.EtiquetaCodigosBarra)
                .HasForeignKey(d => d.FK_IdEtiqueta)
                .HasConstraintName("FK_EtiquetaCodigosBarra_Etiqueta");

            entity.HasOne(d => d.FK_IdTipoCodigoBarraNavigation).WithMany(p => p.EtiquetaCodigosBarra)
                .HasForeignKey(d => d.FK_IdTipoCodigoBarra)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EtiquetaCodigosBarra_TipoCodigoBarra");
        });

        modelBuilder.Entity<EtiquetaLabels>(entity =>
        {
            entity.HasKey(e => e.PK_IdEtiquetaLabel).HasName("PK__Etiqueta__CAC7DFA5E672572C");

            entity.HasIndex(e => new { e.FK_IdEtiqueta, e.FK_IdTipoLabel, e.FK_IdIdioma }, "UQ_Etiqueta_Tipo_Idioma").IsUnique();

            entity.HasOne(d => d.FK_IdEtiquetaNavigation).WithMany(p => p.EtiquetaLabels)
                .HasForeignKey(d => d.FK_IdEtiqueta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EtiquetaLabels_Etiqueta");

            entity.HasOne(d => d.FK_IdIdiomaNavigation).WithMany(p => p.EtiquetaLabels)
                .HasForeignKey(d => d.FK_IdIdioma)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EtiquetaLabels_Idioma");

            entity.HasOne(d => d.FK_IdLabelNavigation).WithMany(p => p.EtiquetaLabels)
                .HasForeignKey(d => d.FK_IdLabel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EtiquetaLabels_LabelsMaster");

            entity.HasOne(d => d.FK_IdTipoLabelNavigation).WithMany(p => p.EtiquetaLabels)
                .HasForeignKey(d => d.FK_IdTipoLabel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EtiquetaLabels_TipoLabel");
        });

        modelBuilder.Entity<HistoricoImpresion>(entity =>
        {
            entity.HasKey(e => e.PK_IdHistoricoImpresion).HasName("PK__Historic__2507519AB22DF44D");

            entity.Property(e => e.Cliente).HasMaxLength(50);
            entity.Property(e => e.CodigoOrden)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CodigoProducto)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Envasado).HasMaxLength(50);
            entity.Property(e => e.FechaImpresion).HasColumnType("datetime");
            entity.Property(e => e.IpMaquina)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.JsonPeticionBartender).IsRequired();
            entity.Property(e => e.JsonRespuestaBartender).IsRequired();
            entity.Property(e => e.NombreEquipo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NombreEtiqueta).HasMaxLength(50);
            entity.Property(e => e.NombrePlantilla)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OvaloCE)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OvaloIdioma)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.OvaloPlanta)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RutaArchivo)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Seccion).HasMaxLength(50);
            entity.Property(e => e.TipoConservacion).HasMaxLength(50);
            entity.Property(e => e.TipoEtiqueta)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UsuarioEtiqueta)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UsuarioPlanta)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UsuarioWindows)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FK_IdEtiquetaNavigation).WithMany(p => p.HistoricoImpresion)
                .HasForeignKey(d => d.FK_IdEtiqueta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Historico_Etiqueta");
        });

        modelBuilder.Entity<IdiomasLabels>(entity =>
        {
            entity.HasKey(e => e.PK_IdIdioma).HasName("PK__IdiomasL__3BF17E42A16D14F9");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LabelsMaster>(entity =>
        {
            entity.HasKey(e => e.PK_IdLabel).HasName("PK__LabelsMa__22FFDE6261E5FBE0");

            entity.HasIndex(e => new { e.FK_IdTipoLabel, e.FK_IdIdioma }, "UQ_Label_Tipo_Idioma").IsUnique();

            entity.Property(e => e.DescripcionLabel)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.FK_IdIdiomaNavigation).WithMany(p => p.LabelsMaster)
                .HasForeignKey(d => d.FK_IdIdioma)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LabelsMaster_Idioma");

            entity.HasOne(d => d.FK_IdTipoLabelNavigation).WithMany(p => p.LabelsMaster)
                .HasForeignKey(d => d.FK_IdTipoLabel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LabelsMaster_TipoLabel");
        });

        modelBuilder.Entity<Plantilla>(entity =>
        {
            entity.HasKey(e => e.PK_IdPlantilla).HasName("PK__Plantill__D86AB92F29DB03DA");

            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.NombrePlantilla)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RutaArchivo)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.UsuarioCreacion).HasMaxLength(50);
            entity.Property(e => e.UsuarioModificacion).HasMaxLength(50);
        });

        modelBuilder.Entity<PlantillaCampos>(entity =>
        {
            entity.HasKey(e => e.PK_IdPlantillaCampo).HasName("PK__Plantill__631B43FF2CD328F3");

            entity.Property(e => e.NombreCampoBartender).HasMaxLength(100);

            entity.HasOne(d => d.FK_IdCampoNavigation).WithMany(p => p.PlantillaCampos)
                .HasForeignKey(d => d.FK_IdCampo)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Plantilla_Campos");

            entity.HasOne(d => d.FK_IdPlantillaNavigation).WithMany(p => p.PlantillaCampos)
                .HasForeignKey(d => d.FK_IdPlantilla)
                .HasConstraintName("FK_PlantillaCampos_Plantilla");
        });

        modelBuilder.Entity<Secciones>(entity =>
        {
            entity.HasKey(e => e.PK_IdSeccion).HasName("PK__Seccione__725830319E727CB2");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TiposCampo>(entity =>
        {
            entity.HasKey(e => e.PK_IdTipoCampo).HasName("PK__TiposCam__18FFE2A1579E2D37");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TiposCodigoBarra>(entity =>
        {
            entity.HasKey(e => e.PK_IdTipoCodigoBarra).HasName("PK__TiposCod__AD5BECF96B0D4F26");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<TiposConservacion>(entity =>
        {
            entity.HasKey(e => e.PK_IdConservacion).HasName("PK__TiposCon__ED89695F6D4F037F");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TiposEnvasado>(entity =>
        {
            entity.HasKey(e => e.PK_IdEnvasado).HasName("PK__TiposEnv__3214EC27221371F6");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TiposEtiqueta>(entity =>
        {
            entity.HasKey(e => e.PK_IdTipoEtiqueta).HasName("PK__TiposEti__9EBDD5E6F1F88073");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TiposLabels>(entity =>
        {
            entity.HasKey(e => e.PK_IdTipoLabel).HasName("PK__TiposLab__1D1199361D8C2C0A");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Ubicaciones>(entity =>
        {
            entity.HasKey(e => e.PK_IdUbicacion);

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(250);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}